apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alphaagent
resources:
  - base.yaml
  - kafka.yaml
  - workloads.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/honggihyuk/inhallmagent
    newTag: latest
